/**
 * Data mapping utilities for Research Contributions Module
 * Standardized data transformation from API responses to UI format
 */

export const mapPatentsData = (item: any, index: number) => ({
  id: item.Pid,
  srNo: index + 1,
  title: item.title || "",
  level: item.Expr2 || "",
  levelId: item.level,
  status: item.name || "",
  statusId: item.status,
  date: item.date ? new Date(item.date).toISOString().split('T')[0] : "",
  Tech_Licence: item.Tech_Licence || "",
  Earnings_Generate: item.Earnings_Generate?.toString() || "",
  PatentApplicationNo: item.PatentApplicationNo || "",
  supportingDocument: item.doc ? [item.doc] : [],
  doc: item.doc,
})

export const mapPoliciesData = (item: any, index: number) => ({
  id: item.Id,
  srNo: index + 1,
  title: item.Title || "",
  level: item.Level || "",
  levelId: null,
  organisation: item.Organisation || "",
  date: item.Date ? new Date(item.Date).toISOString().split('T')[0] : "",
  supportingDocument: item.Doc ? [item.Doc] : [],
  doc: item.Doc,
})

export const mapEContentData = (item: any, index: number) => ({
  id: item.Eid,
  srNo: index + 1,
  title: item.title || "",
  Brief_Details: item.Brief_Details || "",
  Quadrant: item.Quadrant,
  Publishing_date: item.Publishing_date ? new Date(item.Publishing_date).toISOString().split('T')[0] : "",
  Publishing_Authorities: item.Publishing_Authorities || "",
  link: item.link || "",
  type_econtent: item.type_econtent,
  type_econtent_name: item.EcontentTypeName || "",
  e_content_type: item.e_content_type,
  e_content_type_name: item.Econtent_PlatformName || "",
  supportingDocument: item.doc ? [item.doc] : [],
  doc: item.doc,
})

export const mapConsultancyData = (item: any, index: number) => ({
  id: item.id,
  srNo: index + 1,
  title: item.name || "",
  name: item.name || "",
  collaborating_inst: item.collaborating_inst || "",
  collaboratingInstitute: item.collaborating_inst || "",
  address: item.address || "",
  Start_Date: item.Start_Date ? new Date(item.Start_Date).toISOString().split('T')[0] : "",
  startDate: item.Start_Date ? new Date(item.Start_Date).toISOString().split('T')[0] : "",
  duration: item.duration || null,
  amount: item.amount || "",
  outcome: item.outcome || "",
  detailsOutcome: item.outcome || "",
  supportingDocument: item.doc ? [item.doc] : [],
  doc: item.doc,
})

export const mapCollaborationsData = (item: any, index: number) => ({
  id: item.id,
  srNo: index + 1,
  category: item.category || "",
  collaboratingInstitute: item.collaborating_inst || "",
  collaborating_inst: item.collaborating_inst || "",
  nameOfCollaborator: item.collab_name || "",
  collab_name: item.collab_name || "",
  qsTheRanking: item.collab_rank || "",
  collab_rank: item.collab_rank || "",
  address: item.address || "",
  details: item.details || "",
  collaborationOutcome: item.Collaborations_Outcome_Name || "",
  collab_outcome: item.collab_outcome,
  Collaborations_Outcome_Id: item.Collaborations_Outcome_Id,
  status: item.collab_status || "",
  collab_status: item.collab_status || "",
  startingDate: item.starting_date ? new Date(item.starting_date).toISOString().split('T')[0] : "",
  starting_date: item.starting_date ? new Date(item.starting_date).toISOString().split('T')[0] : "",
  duration: item.duration || null,
  level: item.Collaborations_Level_Id || item.level,
  Collaborations_Level_Id: item.Collaborations_Level_Id,
  levelName: item.Collaborations_Level_Name || "",
  type: item.type,
  noOfBeneficiary: item.beneficiary_num || null,
  beneficiary_num: item.beneficiary_num || null,
  mouSigned: item.MOU_signed ? "Yes" : "No",
  MOU_signed: item.MOU_signed,
  signingDate: item.signing_date ? new Date(item.signing_date).toISOString().split('T')[0] : "",
  signing_date: item.signing_date ? new Date(item.signing_date).toISOString().split('T')[0] : "",
  supportingDocument: item.doc ? [item.doc] : [],
  doc: item.doc,
  DocVisible: item.DocVisible,
})

export const mapVisitsData = (item: any, index: number) => ({
  id: item.id,
  srNo: index + 1,
  instituteVisited: item.Institute_visited || "",
  Institute_visited: item.Institute_visited || "",
  durationOfVisit: item.duration || null,
  duration: item.duration || null,
  role: item.Acad_research_Role_Id || item.role,
  Acad_research_Role_Id: item.Acad_research_Role_Id,
  roleName: item.Acad_research_Role_Name || "",
  sponsoredBy: item.Sponsored_by || "",
  Sponsored_by: item.Sponsored_by || "",
  remarks: item.remarks || "",
  date: item.date ? new Date(item.date).toISOString().split('T')[0] : "",
  supportingDocument: item.doc ? [item.doc] : [],
  doc: item.doc,
  DocVisible: item.DocVisible,
})

export const mapFinancialSupportData = (item: any, index: number) => ({
  id: item.id,
  srNo: index + 1,
  nameOfSupport: item.name || "",
  name: item.name || "",
  type: item.Financial_Support_Type_Id || item.type,
  Financial_Support_Type_Id: item.Financial_Support_Type_Id,
  typeName: item.Financial_Support_Type_Name || "",
  supportingAgency: item.support || "",
  support: item.support || "",
  grantReceived: item.grant_received || null,
  grant_received: item.grant_received || null,
  detailsOfEvent: item.details || "",
  details: item.details || "",
  purposeOfGrant: item.purpose || "",
  purpose: item.purpose || "",
  date: item.date ? new Date(item.date).toISOString().split('T')[0] : "",
  supportingDocument: item.doc ? [item.doc] : [],
  doc: item.doc,
  DocVisible: item.DocVisible,
})

export const mapJrfSrfData = (item: any, index: number) => ({
  id: item.id,
  srNo: index + 1,
  nameOfFellow: item.name || "",
  name: item.name || "",
  type: item.JRF_SRF_Type_Id || item.type,
  JRF_SRF_Type_Id: item.JRF_SRF_Type_Id,
  typeName: item.JRF_SRF_Type_Name || "",
  projectTitle: item.title || "",
  title: item.title || "",
  duration: item.duration || null,
  monthlyStipend: item.stipend || null,
  stipend: item.stipend || null,
  date: item.date ? new Date(item.date).toISOString().split('T')[0] : "",
  supportingDocument: item.doc ? [item.doc] : [],
  doc: item.doc,
  DocVisible: item.DocVisible,
})

export const mapPhdGuidanceData = (item: any, index: number) => ({
  id: item.id,
  srNo: index + 1,
  regNo: item.regno || "",
  regno: item.regno || "",
  nameOfStudent: item.name || "",
  name: item.name || "",
  dateOfRegistration: item.start_date ? new Date(item.start_date).toISOString().split('T')[0] : "",
  start_date: item.start_date ? new Date(item.start_date).toISOString().split('T')[0] : "",
  topic: item.topic || "",
  status: item.Res_Proj_Other_Details_Status_Id || item.status,
  Res_Proj_Other_Details_Status_Id: item.Res_Proj_Other_Details_Status_Id,
  statusName: item.Res_Proj_Other_Details_Status_Name || "",
  yearOfCompletion: item.year_of_completion || null,
  year_of_completion: item.year_of_completion || null,
  supportingDocument: item.doc ? [item.doc] : [],
  doc: item.doc,
  DocVisible: item.DocVisible,
})

export const mapCopyrightsData = (item: any, index: number) => ({
  id: item.Id || item.id,
  srNo: index + 1,
  title: item.Title || "",
  Title: item.Title || "",
  referenceNo: item.RefNo || "",
  RefNo: item.RefNo || "",
  publicationDate: item.PublicationDate ? new Date(item.PublicationDate).toISOString().split('T')[0] : "",
  PublicationDate: item.PublicationDate ? new Date(item.PublicationDate).toISOString().split('T')[0] : "",
  link: item.Link || "",
  Link: item.Link || "",
  supportingDocument: item.doc ? [item.doc] : [],
  doc: item.doc,
  DocVisible: item.DocVisible,
})

export const DATA_MAPPERS = {
  patents: mapPatentsData,
  policy: mapPoliciesData,
  econtent: mapEContentData,
  consultancy: mapConsultancyData,
  collaborations: mapCollaborationsData,
  visits: mapVisitsData,
  financial: mapFinancialSupportData,
  jrfSrf: mapJrfSrfData,
  phd: mapPhdGuidanceData,
  copyrights: mapCopyrightsData,
} as const

export const API_DATA_KEYS = {
  patents: 'patents',
  policy: 'policies',
  econtent: 'eContent',
  consultancy: 'consultancies',
  collaborations: 'collaborations',
  visits: 'visits',
  financial: 'financialSupports',
  jrfSrf: 'jrfSrfs',
  phd: 'phdStudents',
  copyrights: 'copyrights',
} as const

